
services:
  reminder-rabbitmq:
    image: rabbitmq:3-management
    hostname: reminder-rabbitmq
    container_name: reminder-rabbitmq
    restart: always
    env_file:
      - .env
    environment:
      - RABBITMQ_SERVER_ADDITIONAL_ERL_ARGS=-rabbit disk_free_limit 536870912
    volumes:
      - ./reminder-service/rabbitmq:/var/lib/rabbitmq
    ports:
      - 15683:15672   
      - 5673:5672
    networks:
      - reminder-network

  reminder-redis:
    image: redis:7
    container_name: reminder-redis
    restart: always
    ports:
      - 6380:6379
    volumes:
      - reminder-redis-data:/data
    command: ["redis-server", "--appendonly", "yes"]
    networks:
      - reminder-network

  reminder-service:
    build:
      context: ./reminder-service
      dockerfile: Dockerfile
    container_name: reminder-service
    restart: always
    env_file:
      - .env
    environment:
      - RABBITMQ_HOST=reminder-rabbitmq
      - RABBITMQ_PORT=5672
      - REDIS_HOST=reminder-redis
      - REDIS_PORT=6379
    ports:
      - "8080:8080"
    volumes:
      - ./.env:/app/.env:ro
    depends_on:
      - reminder-rabbitmq
      - reminder-redis
    networks:
      - reminder-network

networks:
  reminder-network:
    driver: bridge

volumes:
  reminder-redis-data:

